Support date/time logical types in avro
airbytehq/json-avro-converter pull request #9
Opened 2021-11-15 17:25 UTC by VitaliiMaltsev

2021-11-17 08:46 UTC, tuliren requested changes

2021-11-17 08:46 UTC, tuliren commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java
> +                    read(avroExtraPropsField, AdditionalPropertyField.FIELD_SCHEMA, additionalProps, path, false));
Nitpick. Can you revert this format change?

2021-11-17 08:46 UTC, tuliren commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java
> +                if (logicalType != null && logicalType.equals(LogicalTypes.timestampMillis())) {
This should be `timestamp-micros` instead of `timestamp-millis`, right? In https://github.com/airbytehq/airbyte/pull/7732, the three chosen logical types are:

```java
case "date-time" -> LogicalTypes.timestampMicros().addToSchema(Schema.create(Schema.Type.LONG));
case "date" -> LogicalTypes.date().addToSchema(Schema.create(Schema.Type.INT));
case "time" -> LogicalTypes.timeMicros().addToSchema(Schema.create(Schema.Type.LONG));
```

which does not include `timestamp-millis`.

2021-11-17 08:46 UTC, tuliren commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java
> +                }
Can you add a comment here why we only expect the `time-micros` and `timestamp-micro` (if my previous comment is correct)?

Something like:

> Only "time-micros" and "timestamp-micro" logical types are expected here, because the Avro schema is converted from a Json schema, and the two logical types corresponds to the Json "time" and "date-time" formats.

2021-11-17 08:46 UTC, tuliren commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/util/DateTimeUtils.java
> +        return Objects.requireNonNull(instant).toEpochMilli();
It is possible to return `null` here, if the `dateTime` is an invalid string.

I think it is fine if the input is invalid. In general, we want to help users sync their data as much as possible, even if some of the data has minor errors. One way to do this is:
1. When generate an Avro field for these logical types, make them a union of `string` and the logical type:
    `["null", { "type" : "long", "logicalType" : "timestamp-micros" }, "string"]`
    Note that `string` must be after the logical type.
2. In the `DateTimeUtils`, if the input is invalid, just return `null`.
3. The `JsonGenericRecordReader` can correctly handle the case. The `readUnion` method will consider each type one by one. It will try to convert the string to the logical type first. When that is null, it will just set the value to the original string. That's why in the first bullet, the logical type must be before the `string` in the type union.

Let me know if it makes sense or if it actually does not work.

2021-11-17 08:46 UTC, tuliren commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/util/DateTimeUtils.java
> +    public static Long getEpochMillis(String dateTime) {
Can you add a comment for each of the three methods in this class about what they are doing?

2021-11-17 08:46 UTC, tuliren commented on converter/src/test/java/tech/allegro/schema/json2avro/converter/DateTimeUtilsTest.java
> +}
Nitpick. Add a newline at the end of this file.

2021-11-17 08:46 UTC, tuliren commented on converter/src/test/resources/json_avro_converter.json
> +  ,{
To keep a consistent format, this comma should be moved to the end of the previous curly brackets.

2021-11-17 08:46 UTC, tuliren commented on converter/src/test/resources/json_avro_converter.json
> +},
The above test case does not have the correct indentation. Should add two spaces to it.

2021-11-17 08:46 UTC, tuliren commented on converter/src/test/resources/json_avro_converter.json
> +  }
Nitpick. I have two general suggestions for the three new test cases.
1. They can just test the logical type field. All other fields (`username`, `age`, `active`) can be removed so that it is more what they are trying to test.
2. The name of the test cases should be concise. The `simple_schema_with` prefix can be removed. Maybe name them like `logical_type_date`.

2021-11-17 12:50 UTC, VitaliiMaltsev commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java
> +                }
done

2021-11-17 12:51 UTC, VitaliiMaltsev commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java
> +                }
done

2021-11-17 12:53 UTC, VitaliiMaltsev commented on converter/src/test/resources/json_avro_converter.json
> +  }
removed redundant fields and renamed test cases

2021-11-17 12:54 UTC, VitaliiMaltsev commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java
> +                    read(avroExtraPropsField, AdditionalPropertyField.FIELD_SCHEMA, additionalProps, path, false));
done

2021-11-17 12:55 UTC, VitaliiMaltsev commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/JsonGenericRecordReader.java
> +                if (logicalType != null && logicalType.equals(LogicalTypes.timestampMillis())) {
you are right. Changed to timestamp-micros

2021-11-17 12:57 UTC, VitaliiMaltsev commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/util/DateTimeUtils.java
> +        return Objects.requireNonNull(instant).toEpochMilli();
DateTimeUtils methods now return null in case of invalid data and value converts to string in avro record.
Added test case for this behaviour

2021-11-17 12:58 UTC, VitaliiMaltsev commented on converter/src/main/java/tech/allegro/schema/json2avro/converter/util/DateTimeUtils.java
> +    public static Long getEpochMillis(String dateTime) {
done

2021-11-17 12:58 UTC, VitaliiMaltsev commented on converter/src/test/java/tech/allegro/schema/json2avro/converter/DateTimeUtilsTest.java
> +}
done

2021-11-17 12:58 UTC, VitaliiMaltsev commented on converter/src/test/resources/json_avro_converter.json
> +  ,{
done

2021-11-17 12:59 UTC, VitaliiMaltsev commented on converter/src/test/resources/json_avro_converter.json
> +},
done

2021-11-30 06:25 UTC, tuliren approved these changes
Looks great! Thanks.

2021-11-30 06:25 UTC, merged